name: CI

on:
  push:
    branches: [ main, master, feat/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Show Node/npm versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build dist (prod)
        run: node build-dist.mjs --prod

      - name: Verify dist (ESM-only)
        run: |
          chmod +x ./scripts/verify-dist.sh || true
          ./scripts/verify-dist.sh dist/prod

      - name: Run tests
        run: npm test --silent

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            dist/prod
            npm-debug.log
            yarn-error.log

  docker-smoke:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build dist (prod)
        run: node build-dist.mjs --prod

      - name: Build Docker image
        run: |
          docker build -t cohere-app:smoke .

      - name: Run container
        run: |
          docker run -d --name cohere-app-smoke -p 3000:3000 --env-file dist/prod/.env cohere-app:smoke || docker run -d --name cohere-app-smoke -p 3000:3000 cohere-app:smoke

      - name: Wait for /health
        run: |
          set -e
          for i in $(seq 1 30); do
            echo "Attempt $i: checking http://localhost:3000/health"
            if curl --fail --silent http://localhost:3000/health >/dev/null; then
              echo "Health check passed"
              exit 0
            fi
            sleep 2
          done
          echo "Health check failed after timeout"
          docker logs --tail 200 cohere-app-smoke || true
          docker ps -a || true
          exit 1

      - name: Stop container
        if: always()
        run: |
          docker rm -f cohere-app-smoke || true
